---
- name: "Deploy letsencrypt cert to Helpdesk"
  vars_files:
    - "vars/letsencrypt.yml"
    - "vars/cert-deploy-rproxy_vars.yml"

  vars:
    host: "rproxy"

  become: true

  hosts: "{{ host }}"

  handlers:
    - ansible.builtin.import_tasks: "tasks/cert-deploy-rproxy_handlers.yml"

  tasks:
    - ansible.builtin.import_tasks: "tasks/cert-deploy-rproxy_tasks.yml"
