---
- name: "Deploy to SMTP Relay"
  vars_files:
    - "vars/cert-cmsd.bc.ca.yml"
    - "vars/letsencrypt.yml"
  
  vars:
    host: "internalrelay"

  become: true

  hosts: "{{ host }}"
  
  handlers:
    - ansible.builtin.import_tasks: "tasks/cert-deploy-smpt-relay_handlers.yml"
  
  tasks:
    - ansible.builtin.import_tasks: "tasks/cert-deploy-smtp-relay_tasks.yml"
