---
- name: "Deploy public key to Windows servers"
  collections:
    - "community.windows"

  vars:
    host: "winservers"
    sshuser: "admin"
    # pubkey_path: "~/.ssh/id_ed25519.pub"
    pubkey_path: "files/pubkeys/it_ccs.pub"
    pubkey: "{{ (lookup('file', pubkey_path)).split() }}"
    remote_auth_keys_path: "{{ ansible_facts.env.ProgramData }}\\ssh\\administrators_authorized_keys"
    # ansible_connection: winrm
    # ansible_winrm_scheme: http
    # ansible_port: 5985
    # ansible_winrm_transport: credssp
  
  hosts: "{{ host }}"

  handlers:
    - name: "restart sshd"
      ansible.windows.win_service:
        name: "sshd"
        state: "restarted"
  
  tasks:
    - name: "Deploy public key to administrators_authorized_keys"
      community.windows.win_lineinfile:
        create: true
        line: "{{ pubkey|join(' ') }}"
        newline: "unix"
        path: "{{ remote_auth_keys_path }}"
        regexp: "{{ pubkey[1] }}"
        state: "present"
      notify: [ "restart sshd" ]

    - name: "Configure proper permissions for administrators_authorized_keys"
      ansible.windows.win_acl:
        path: "{{ remote_auth_keys_path }}"
        rights: "FullControl"
        state: "present"
        type: "allow"
        user: "{{ item }}"
      loop:
        - "BUILTIN\\Administrators"
        - "NT AUTHORITY\\SYSTEM"
    
    - name: "Remove inheritence on the administrators_authorized_keys file"
      ansible.windows.win_acl_inheritance:
        path: "{{ remote_auth_keys_path }}"
        reorganize: false
        state: "absent"
