---
- name: "Deploy Public Key To Linux Server(s)"

  vars:
    host: "lin_servers"
    sshuser: "root"
    pubkey_path: "~/.ssh/id_ed25519.pub"
    # pubkey_path: "files/erolleman_nisgaa.pub"

  hosts: "{{ host }}"

  tasks:
    - name: "Add public key to authorized_keys"
      ansible.builtin.authorized_key:
        user: "{{ sshuser }}"
        state: "present"
        manage_dir: yes
        key: "{{ lookup('file', pubkey_path) }}"
