---
- name: "Setup VIM environment"
  vars_files:
    - "vars/vim.yaml"
  
  vars:
    host: "localhost"

  hosts: "{{ host }}"
  
  gather_facts: true

  tasks:
    - ansible.builtin.import_tasks: "tasks/vim-setup-environment_tasks.yml"

    - ansible.builtin.import_tasks: "tasks/vim-download-codedark_tasks.yml"

    - ansible.builtin.import_tasks: "tasks/vim-install-codedark_tasks.yml"
