- name: "Get fail information"
  ansible.builtin.set_fact:
    fail_message: |
      {{ report_prefix }} Failed to deploy certificate on task '{{ x_task }}'. {{ x_err }}
  vars:
    # x_err: "{{ ansible_failed_result|json_query('results[].msg')|join('\n') }}"
    x_err: "{{ ansible_failed_result.msg }}"
    x_task: "{{ ansible_failed_task['name'] }}"

- name: "Record fail entry in report file"
  delegate_to: "localhost"
  ansible.builtin.lineinfile:
    create: true
    mode: 0700
    insertafter: "EOF"
    line: "{{ fail_message }}"
    path: "{{ certdeploy_report_path }}"
    state: "present"